name: Build and Deploy Bicep to GitHub Pages

on:
  push:
#    paths:
#      - 'bicep/**/*.bicep'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
            bicepFilePath: bicep/main.bicep
            outputFilePath: deploy/azuredeploy.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy