name: Deploy Cloudflare Worker

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # OIDC経由の認証用
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm install

      - name: create wrangler.toml
        run: |
            cp wrangler.toml.template wrangler.toml
            sed -i "s/\\$\\{\\{KV_NAMESPACE_ID\\}\\}/${KV_NAMESPACE_ID}/g" wrangler.toml
            sed -i "s/\\$\\{\\{R2_BUCKET_NAME\\}\\}/${R2_BUCKET_NAME}/g" wrangler.toml
            sed -i "s/\\$\\{\\{SEND_MODE\\}\\}/${SEND_MODE}/g" wrangler.toml
        env:
            KV_NAMESPACE_ID: ${{ vars.KV_NAMESPACE_ID }}
            R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
            SEND_MODE: ${{ vars.SEND_MODE }}

      - name: wrangler types
        run: npm run wrangler-types

      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '3'
          postCommands: |
            echo "Deploying with GitHub OIDC"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          # API Tokenを使用せず、GitHub ActionsのOIDCを使用